title: 'Page Settings'
fields:
  -
    handle: navigation_image
    field:
      mode: list
      container: assets
      restrict: false
      allow_uploads: true
      show_filename: true
      max_files: 1
      display: 'Navigation Image'
      type: assets
      icon: assets
      width: 50
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: navigation_color
    field:
      theme: classic
      lock_opacity: false
      default_color_mode: HEXA
      color_modes:
        - hex
      display: 'Navigation Color'
      type: color
      icon: color
      width: 50
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: background_color
    field:
      theme: classic
      lock_opacity: false
      default_color_mode: HEXA
      color_modes:
        - hex
      display: 'Page Background Color'
      type: color
      icon: color
      width: 50
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: page_copy_color
    field:
      theme: classic
      lock_opacity: false
      default_color_mode: HEXA
      color_modes:
        - hex
      display: 'Page Copy Color'
      type: color
      icon: color
      width: 50
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
